name: Tag Release & Push Gem

on: workflow_dispatch

jobs:
  release:
    name: Validate Docs, Tag, and Push Gem
    runs-on: ubuntu-latest
    if: github.repository == 'puppetlabs/beaker-answers'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        clean: true
        fetch-depth: 0

    - name: Get New Version
      id: nv
      run: |
        version=$(grep STRING lib/beaker-answers/version.rb |rev |cut -d "'" -f2 |rev)
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "Found version $version from lib/beaker-answers/version.rb"

    - name: Get Current Version
      uses: actions/github-script@v7
      id: cv
      with:
        script: |
          const { data: response } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          console.log(`The latest release is ${response.tag_name}`)
          return response.tag_name
        result-encoding: string

    - name: Tag Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.nv.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        version: 2.7.x

    - name: Build gem
      run: gem build *.gemspec

    - name: Publish gem
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
